// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXTbUiYiKl-aH03ZCeg-qrWhzwVQPktqY',
    appId: '1:495635186767:web:dd300b3db751517163963a',
    messagingSenderId: '495635186767',
    projectId: 'college-connect-a1d70',
    authDomain: 'college-connect-a1d70.firebaseapp.com',
    storageBucket: 'college-connect-a1d70.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOstKVbuc-TDNPeJPwi2_rnzmDF3fGaxk',
    appId: '1:495635186767:android:1ae6064b5af6fd9e63963a',
    messagingSenderId: '495635186767',
    projectId: 'college-connect-a1d70',
    storageBucket: 'college-connect-a1d70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0iJjwJjCvPW4tDIwsurLEbXCUP0XWosg',
    appId: '1:495635186767:ios:230f146ebdd28db963963a',
    messagingSenderId: '495635186767',
    projectId: 'college-connect-a1d70',
    storageBucket: 'college-connect-a1d70.firebasestorage.app',
    iosBundleId: 'com.example.campusConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0iJjwJjCvPW4tDIwsurLEbXCUP0XWosg',
    appId: '1:495635186767:ios:230f146ebdd28db963963a',
    messagingSenderId: '495635186767',
    projectId: 'college-connect-a1d70',
    storageBucket: 'college-connect-a1d70.firebasestorage.app',
    iosBundleId: 'com.example.campusConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXTbUiYiKl-aH03ZCeg-qrWhzwVQPktqY',
    appId: '1:495635186767:web:ba67926ffa5ac1f663963a',
    messagingSenderId: '495635186767',
    projectId: 'college-connect-a1d70',
    authDomain: 'college-connect-a1d70.firebaseapp.com',
    storageBucket: 'college-connect-a1d70.firebasestorage.app',
  );
}
